name: appium-android CI

on:
  push:
    branches: [ "mvn" ]
  pull_request:
    branches: [ "mvn" ]

jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        api-level: [30]
        target: [default]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/setup-node@v2
        with:
          node-version: '21.7.1'
      - run: |
          npm install -g appium@2.4.1
          appium driver install uiautomator2
          appium driver install xcuitest
          appium -v
          appium &>/dev/null &
      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          headless: true
          disable-animations: true
          script: adb shell getprop sys.boot_completed | grep -m 1 '1' || echo 'Waiting for emulator to boot...'
      - name: Run Tests
        run: mvn clean test -Pandroid
