# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Appium iOS 

on:
  push:
    branches: [ "mvn" ]
  pull_request:
    branches: [ "mvn" ]

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/setup-node@v2
        with:
          node-version: '21.7.1'
      - run: |
          npm install -g appium@2.4.1
          appium -v
          appium --port 4723 &
          mvn clean test -PiOS
